/* Generated By:JavaCC: Do not edit this line. SemgrexParserConstants.java */
package edu.stanford.nlp.semgraph.semgrex;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface SemgrexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int UNIQ = 2;
  /** RegularExpression Id. */
  int SORT = 3;
  /** RegularExpression Id. */
  int RSORT = 4;
  /** RegularExpression Id. */
  int RELATION = 5;
  /** RegularExpression Id. */
  int ALIGNRELN = 6;
  /** RegularExpression Id. */
  int IDENTIFIER = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int EMPTY = 9;
  /** RegularExpression Id. */
  int ROOT = 10;
  /** RegularExpression Id. */
  int REGEX = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"uniq\"",
    "\"sort\"",
    "\"rsort\"",
    "<RELATION>",
    "\"@\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"#\"",
    "\"$\"",
    "<REGEX>",
    "\":\"",
    "\"::\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"&\"",
    "\"!\"",
    "\"?\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"~\"",
    "\"=\"",
    "\"!:\"",
    "\"%\"",
    "\":{\"",
    "\";\"",
    "\"}\"",
    "\"{\"",
  };

}
